version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: mis-finanzas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: 172.19.0.2
      DB_PORT: 5432
      DB_USERNAME: dbuser
      DB_PASSWORD: dbpass
      DB_NAME: mis-finanzas
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    profiles:
      - do-not-start

volumes:
  postgres_data:
